#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "DeviceLock" \
  --arg udid "$1" \
  --arg pin $2 \
  '.udid = $udid 
  |.pin = $pin 
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -K <(cat <<< "-u micromdm:$API_TOKEN") "$SERVER_URL/$endpoint" -d@-
