#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ProfileList" \
  --arg udid "$1" \
  '.udid = $udid
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS \
    -H "Content-Type: application/json" \
    -K <(cat <<< "-u \"micromdm:$API_TOKEN\"") "$SERVER_URL/$endpoint" -d@-
