#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "RemoveProvisioningProfile" \
  --arg udid "$1" \
  --arg uuid $2 \
  '.udid = $udid
  |.uuid = $uuid
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -K <(cat <<< "-u micromdm:$API_TOKEN") "$SERVER_URL/$endpoint" -d@-
