#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "SetBootstrapToken" \
  --arg udid "$1" \
  --arg token "$2" \
 '.udid = $udid 
  |.request_type = $request_type
  |.bootstrap_token = $token
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
